In [2]:
import numpy as np

In [3]:
ari=np.array(6)

In [4]:
ari

array(6)

In [5]:
type(ari)

numpy.ndarray

In [6]:
ari2=np.array([2,3,5,6,7])

In [7]:
ari2

array([2, 3, 5, 6, 7])

In [8]:
ari3=np.array([[2,3,5,6],[1,4,8,9]])

In [9]:
ari3

array([[2, 3, 5, 6],
       [1, 4, 8, 9]])

# array types 

1.zero array
2.ones array
3.empty array
4.array for range

#  ZERO ARRAY

In [10]:
ar_zero=np.zeros((2,2))

In [11]:
ar_zero

array([[0., 0.],
       [0., 0.]])

#  RANGE ARRAY

In [12]:
ar_range=np.arange(2,15,2)

In [13]:
ar_range

array([ 2,  4,  6,  8, 10, 12, 14])

# transpose of  array

In [14]:
ari3

array([[2, 3, 5, 6],
       [1, 4, 8, 9]])

In [15]:
ar5=np.transpose(ari3)

In [16]:
ar5

array([[2, 1],
       [3, 4],
       [5, 8],
       [6, 9]])

In [17]:
ar6=np.ravel(ar5)

In [18]:
ar6

array([2, 1, 3, 4, 5, 8, 6, 9])

In [19]:
a1=np.array([2,3,4,5])

In [20]:
a2=np.array([9,7,4,5])

In [21]:
hori=np.hstack(a1)#a1,a2

In [22]:
verti=np.vstack(a1)

In [23]:
hori

array([2, 3, 4, 5])

In [24]:
verti

array([[2],
       [3],
       [4],
       [5]])

# determinant and  inverse

In [34]:
mat1=np.array([[6,3,4],[1,3,29],[4,5,6]])

In [35]:
mat1

array([[ 6,  3,  4],
       [ 1,  3, 29],
       [ 4,  5,  6]])

In [36]:
det_df=np.linalg.det(mat1)

In [38]:
det_df

-459.9999999999997